"""add followers

Revision ID: 580da6d343d8
Revises: 611cb57480e1
Create Date: 2019-10-06 14:02:59.752374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580da6d343d8'
down_revision = '611cb57480e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
