"""Added name to recipes

Revision ID: 8f7ad2592639
Revises: 64bc6c67d0d7
Create Date: 2019-07-27 22:39:59.069226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7ad2592639'
down_revision = '64bc6c67d0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_recipe_name'), 'recipe', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_name'), table_name='recipe')
    op.drop_column('recipe', 'name')
    # ### end Alembic commands ###
